contact_links:
  - name: Discord
    url: https://discord.gg/pearai
    about: Feel free to report bugs and request features here!
  - name: Docs
    url: https://docs.pearai.dev
    about: Check out how to self-deploy Sweep, usage guides and best practices
